Add a readme and readme url for sample DAX datasets
machine-learning-exchange/katalog pull request #15
Opened 2021-08-13 23:23 UTC by drewbutlerbb4

Add sample readme and `readme_url` in dataset yaml to allow the UI to access the readme.
Related: https://github.com/machine-learning-exchange/mlx/pull/179

2021-08-13 23:24 UTC, drewbutlerbb4 commented
/assign @ckadner

2021-08-16 15:45 UTC, drewbutlerbb4 commented
@ckadner Please merge this if this is satisfactory. I do not have the privileges to merge.

2021-08-17 07:19 UTC, ckadner requested changes
Thanks @drewbutlerbb4 -- Please update the `readme_url` to point to the main katalog repo ` machine-learning-exchange/katalog` instead of your fork. Otherwise this looks good to me.

2021-08-17 07:19 UTC, ckadner commented on dataset-samples/gmb.yaml
> +readme_url: https://raw.githubusercontent.com/drewbutlerbb4/katalog/readme-url/dataset-samples/gmb.md
aspirationally, update the `readme_url` to main katalog repo ` machine-learning-exchange/katalog` instead of your fork :-)

and add a new line

2021-08-17 07:19 UTC, ckadner commented on dataset-samples/jfk.yaml
> +readme_url: https://raw.githubusercontent.com/drewbutlerbb4/katalog/readme-url/dataset-samples/jfk.md
aspirationally, update the `readme_url` to main katalog repo ` machine-learning-exchange/katalog` instead of your fork :-)

2021-08-17 07:46 UTC, ckadner commented
@kmh4321

2021-08-17 15:33 UTC, drewbutlerbb4 commented
@ckadner thanks

2021-08-17 15:44 UTC, kmh4321 commented on dataset-samples/jfk.md
> +## Related Links
The related links section mostly served up to cross link traffic on IBM Developer. Feel free to drop it if it's not too relevant here.

2021-08-17 15:44 UTC, kmh4321 approved these changes

2021-08-17 15:45 UTC, kmh4321 commented on dataset-samples/jfk.md
> +## Related Links
It is just an option, we can keep it too if it maintains consistency.

2021-08-17 17:49 UTC, ckadner commented on dataset-samples/jfk.md
> +## Related Links
The `Related Links` that point to other MAX/DAX assets could be replaced to point to the corresponding MAX/DAX assets in MLX -- either pointing to `ml-exchange.org` or use relative links that will open the asset within the local MLX UI

2021-08-17 22:35 UTC, drewbutlerbb4 commented
@ckadner The files have been moved to folders now please merge if it looks good to you.

2021-08-17 23:41 UTC, ckadner approved these changes
/lgtm

2021-08-17 23:48 UTC, merged