Add script to update asset list in main readme
machine-learning-exchange/katalog pull request #69
Opened 2022-04-02 22:56 UTC by rafvasq

Adding helper script to update the list of assets on the main README.

Related issue: #45 

FYI @ckadner

2022-04-08 22:58 UTC, ckadner requested changes
Thank you Rafael! This is a great addition to automate and avoid missing to add links to for new assets. There are a few things we still need to change though :-)

2022-04-08 22:58 UTC, ckadner commented on README.md
> +## Components
I think the term "Pipeline Components" was chosen deliberately here (@animeshsingh), so we may need to add an extra condition or mapping to generate that text in your script

2022-04-08 22:58 UTC, ckadner commented on README.md
> -* [Trusted AI Pipeline with AI Fairness 360 and Adversarial Robustness 360 Components](https://github.com/kubeflow/kfp-tekton/tree/master/samples/trusted-ai)
We need to keep (some of) the external pipelines (for now). Maybe the script could print a warning that who ever runs it must exercise some judgment before committing the changes with a warning the external asset links may have been removed unintentionally. 

A better way, albeit more work, might be to have the script read the existing README file, find absolute YAML links which point oustide the `katalog` repo, and re-inject them into the newly generated README. If we don't want to do that now, maybe we can create an issue for it.

We also need an issue to determine whether we want to move those external pipelines into the katalog repo instead. (@animeshsingh @Tomcli)

2022-04-08 22:58 UTC, ckadner commented on README.md
> +* [Launch Katib Early Stopping Experiment](https://raw.githubusercontent.com/machine-learning-exchange/katalog/main/pipeline-samples/katib-pipeline.yaml)
the Katib pipeline, nested pipeline, WML/Watson pipeline might actually be in both this `katalog` repo and in `kfp-tekton` (@Tomcli)

2022-04-08 22:58 UTC, ckadner commented on README.md
> +* [Calculation Pipeline](https://raw.githubusercontent.com/machine-learning-exchange/katalog/main/pipeline-samples/calculation-pipeline.yaml)
we want relative links for all asset YAMLs that reside in the `katalog` repo

2022-04-08 22:58 UTC, ckadner commented on README.md
> +* [ART detector model](https://raw.githubusercontent.com/machine-learning-exchange/katalog/main/notebook-samples/art-detector.yaml)
the asset titles should be in **T**itle **C**ase. Probably best to update the respective YAML files, since we don't want to turn "ART" or "AIF360" into "Art" and "Aif360"

2022-04-08 22:58 UTC, ckadner commented on tools/python/update_asset_list.py
> +
we should add a brief comment describing what this script does

2022-04-08 22:58 UTC, ckadner commented on tools/python/update_asset_list.py
> +                asset_name = yaml_dict.get("name") or yaml_dict.get("metadata", {})\
this does not title case the `yaml_dict.get("name")` so it should be

```Python
    asset_name = yaml_dict.get("name") or yaml_dict.get("metadata", {}).get("name", "")
    asset_name = asset_name.replace("-", " ").title() or ""
```

but I think we should leave the name unchanged here and instead update the YAML files directly

2022-04-08 22:58 UTC, ckadner commented on tools/python/update_asset_list.py
> +                asset_url = KATALOG_URL + relpath(yaml_file, katalog_dir)
we want just relative paths here

2022-04-08 22:58 UTC, ckadner commented on tools/python/update_asset_list.py
> +    f = open("README.md", "w")
the recommended way to read/write a file is to use a `with` statement:

```Python
with open('README.md', 'w') as f:
    f.write("\n".join(md))
```

https://stackoverflow.com/a/6160082

2022-04-08 22:58 UTC, ckadner commented on tools/python/update_asset_list.py
> +        "<!-- Do not edit. This file was generated by ./tools/python/update_asset_list.py "
did you try using one multi-line string here, i.e.

```Python
# import textwrap

    md.append(textwrap.dedent("""\
        <!-- Do not edit. This file was generated by ./tools/python/update_asset_list.py ...
        ...
        # List of Default Catalog Assets"""))

```

2022-04-08 22:58 UTC, ckadner commented on tools/python/update_asset_list.py
> +    print("Regenerating Katalog asset list.\n")
maybe include the file name/path of the README.md we are regenerating

2022-04-13 00:50 UTC, rafvasq commented on README.md
> +* [ART detector model](https://raw.githubusercontent.com/machine-learning-exchange/katalog/main/notebook-samples/art-detector.yaml)
@ckadner Might be a silly question, but should all of the names in the YAMLs should be human-readable right? Meaning that I don't need to follow the `pipeline-name` convention but should use `Pipeline Name` instead?

2022-04-13 21:28 UTC, ckadner commented on README.md
> +* [ART detector model](https://raw.githubusercontent.com/machine-learning-exchange/katalog/main/notebook-samples/art-detector.yaml)
The `name` filed in the YAML files should be the human-readable display name except for the pipeline YAMLs. The pipeline YAMLs are Kubernetes resources spec generated/compiled from pipeline DSL Python scripts. In the pipeline YAML the human readable display name is "tucked away" inside the `metadata.annotations` ...

```YAML
metadata:
  annotations:
    pipelines.kubeflow.org/pipeline_spec: '{"description": "A pipeline that ...", ...
      "name": "My Awesome Pipeline"}'
``` 

i.e. in the WML pipeline sample: `"name": "KFP on WML training"`
https://github.com/machine-learning-exchange/katalog/blob/8917a5dca5d8909ad2fa9f6c6fa80c856f772f98/pipeline-samples/wml-pipeline.yaml#L52-L53

https://github.com/kubeflow/kfp-tekton/blob/4b5230b6941b59fcac2a34a6190665f1ef548217/samples/watson-train-serve/watson_train_serve_pipeline.py#L42

```Python
@dsl.pipeline(
    name='KFP on WML training',
    description='Kubeflow pipelines running on WML performing tensorflow image recognition.'
)
def kfp_wml_pipeline(...
```

2022-04-27 17:16 UTC, ckadner commented on README.md
> -* [Trusted AI Pipeline with AI Fairness 360 and Adversarial Robustness 360 Components](https://github.com/kubeflow/kfp-tekton/tree/master/samples/trusted-ai)
https://github.com/machine-learning-exchange/katalog/issues/70

2022-04-27 17:18 UTC, ckadner commented on README.md
> -* [Trusted AI Pipeline with AI Fairness 360 and Adversarial Robustness 360 Components](https://github.com/kubeflow/kfp-tekton/tree/master/samples/trusted-ai)
these pipelines we currently get from the KFP repo:
https://github.com/machine-learning-exchange/mlx/blob/605fe331d863e62e770607130041d298268b4122/bootstrapper/catalog_upload.json#L162-L174

```YAML
  "pipelines": [
    {
      "name": "Parallel Join",
      "url": "https://github.com/kubeflow/kfp-tekton/blob/master/sdk/python/tests/compiler/testdata/parallel_join.yaml"
    },
    {
      "name": "Sequential Pipeline",
      "url": "https://github.com/kubeflow/kfp-tekton/blob/master/sdk/python/tests/compiler/testdata/sequential.yaml"
    },
    {
      "name": "ResourceOp Basic",
      "url": "https://github.com/kubeflow/kfp-tekton/blob/master/sdk/python/tests/compiler/testdata/resourceop_basic.yaml"
    },
```

2022-05-07 01:11 UTC, closed without merging